type Query {
  currentUser: User
  feed(take: Int!, from: String): FeedConnection!
}

type Mutation {
  createTweet(tweet: CreateTweetInput!): CreateTweetPayload!
  createUser(user: CreateUserInput!): CreateUserPayload!
  updateUserhandle(handle: String!): UpdateUserHandlePayload!
}

input CreateTweetInput {
  body: String!
  visibility: Visibility!
}

input CreateUserInput {
  name: String!
  handle: String
  email: String!
  bio: String
  location: String
  avatarUrl: String
  birthDate: String!
}

type UpdateUserHandlePayload {
  successfull: Boolean!
}

type CreateTweetPayload {
  tweet: Tweet!
  successfull: Boolean!
}

type CreateUserPayload {
  user: User!
  successfull: Boolean!
}

type FeedConnection {
  edges: [FeedEdge!]!
  pageInfo: PageInfo
}

type FeedEdge {
  cursor: String!
  node: Tweet!
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
}

type User {
  id: ID!
  name: String!
  handle: String
  email: String!
  bio: String
  location: String
  avatarUrl: String!
  followersCount: Int!
  followingCount: Int!
  createdAt: String!
  birthDate: String!
}

type Tweet {
  id: ID!
  body: String!
  author: User!
  createdAt: String!
  retweetCount: Int!
  likeCount: Int!
  replyCount: Int!
  visibility: Visibility!
  type: TweetType!
}

enum Visibility {
  PUBLIC
  PRIVATE
}

enum TweetType {
  ORIGINAL
  RETWEET
  REPLY
}